### ISSUE TITLE
Druck-CSS: Inhalt wird im Firefox abgeschnitten

### ISSUE THREAD

**Issue by auge8472** [auge8472/SelfForum#1]
Der Inhalt, der ausgedruckt werden soll, wird im Firefox am Ende der ersten Seite des Ausdrucks abgeschnitten. Das passiert auch beim Druck in eine Datei. Beispiele folgen.

**Comment by MatthiasApsel** [comment]
``` css
@media print {
    .flex-container, 
    article.thread-nested,
    article.thread-message {
        display: block;
    }
}
```

hilft.
